# Generated by Django 4.2.7 on 2024-09-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(db_column='Region_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('soil_ph', models.DecimalField(blank=True, db_column='Soil_ph', decimal_places=2, max_digits=4, null=True)),
                ('water_availability', models.CharField(blank=True, db_column='Water_availability', max_length=255, null=True)),
                ('humidity', models.CharField(blank=True, db_column='Humidity', max_length=255, null=True)),
                ('day_light', models.CharField(blank=True, db_column='Day_light', max_length=255, null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='User_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('image', models.ImageField(blank=True, db_column='Image', null=True, upload_to='user_images/')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('number', models.CharField(db_column='Number', max_length=15)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
