# Generated by Django 4.2.7 on 2024-09-29 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(db_column='Region_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('soil_ph', models.DecimalField(blank=True, db_column='Soil_ph', decimal_places=2, max_digits=4, null=True)),
                ('water_availability', models.CharField(blank=True, db_column='Water_availability', max_length=255, null=True)),
                ('humidity', models.CharField(blank=True, db_column='Humidity', max_length=255, null=True)),
                ('day_light', models.CharField(blank=True, db_column='Day_light', max_length=255, null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='User_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('number', models.CharField(db_column='Number', max_length=15)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatbotInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('question_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chatbot.user')),
            ],
        ),
    ]
