# Generated by Django 4.2.7 on 2024-09-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabourHire',
            fields=[
                ('hire_id', models.AutoField(db_column='Hire_id', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, db_column='Start_date', null=True)),
                ('end_date', models.DateField(blank=True, db_column='End_date', null=True)),
                ('active', models.BooleanField(db_column='Active', default=True)),
            ],
            options={
                'db_table': 'labour_hire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(db_column='Region_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('soil_ph', models.DecimalField(blank=True, db_column='Soil_ph', decimal_places=2, max_digits=4, null=True)),
                ('water_availability', models.CharField(blank=True, db_column='Water_availability', max_length=255, null=True)),
                ('humidity', models.CharField(blank=True, db_column='Humidity', max_length=255, null=True)),
                ('day_light', models.CharField(blank=True, db_column='Day_light', max_length=255, null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='User_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('image', models.ImageField(blank=True, db_column='Image', null=True, upload_to='user_images/')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('number', models.CharField(db_column='Number', max_length=15)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('labour', models.OneToOneField(db_column='Labour_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hire.user')),
                ('specialates', models.TextField(blank=True, db_column='Specialates', null=True)),
                ('preceable_time', models.DateTimeField(blank=True, db_column='Preceable_time', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('demand_fees', models.DecimalField(blank=True, db_column='Demand_fees', decimal_places=2, max_digits=10, null=True)),
                ('rating', models.JSONField(blank=True, db_column='Rating', null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
                ('experience', models.IntegerField(blank=True, db_column='Experience', null=True)),
            ],
            options={
                'db_table': 'labour',
                'managed': False,
            },
        ),
    ]
