# Generated by Django 4.2.7 on 2024-09-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labour',
            options={},
        ),
    ]
