# Generated by Django 4.2.7 on 2024-09-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_alter_labour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labour',
            options={'managed': False},
        ),
    ]
