# Generated by Django 4.2.7 on 2024-09-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0005_alter_labour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labourhire',
            options={},
        ),
    ]
