# Generated by Django 4.2.7 on 2024-09-21 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0006_alter_labourhire_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labourhire',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='labourhire',
            name='hirer',
            field=models.ForeignKey(blank=True, db_column='hirer', null=True, on_delete=django.db.models.deletion.CASCADE, to='hire.user'),
        ),
        migrations.AddField(
            model_name='labourhire',
            name='labour',
            field=models.ForeignKey(blank=True, db_column='Labour_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='hire.labour'),
        ),
        migrations.AddField(
            model_name='labourhire',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('notavailable', 'Not Available'), ('pending', 'Pending')], db_column='Status', default='pending', max_length=255),
        ),
    ]
