# Generated by Django 4.2.7 on 2024-09-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='User_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('number', models.CharField(db_column='Number', max_length=15)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('region_id', models.IntegerField(blank=True, db_column='Region_id', null=True)),
                ('active', models.IntegerField(blank=True, db_column='Active', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
